In [1]:
import numpy as np
from lab2_tools import *
from lab2_proto import *
from tqdm import trange

In [2]:
example = np.load('lab2_example.npz',allow_pickle=True)['example'].item()
samplingrate_ex = example['samplingrate']
gender_ex = example['gender']
speaker_ex = example['speaker']
digit_ex = example['digit']
repetition_ex = example['repetition']
samples_ex = example['samples']
lmfcc_ex = example['lmfcc']

obsloglik_ex = example['obsloglik']
logalpha_ex = example['logalpha']
loglik_ex = example['loglik']
vloglik_ex = example['vloglik']
vpath_ex = example['vpath']
logbeta_ex = example['logbeta']
loggamma_ex = example['loggamma']

# Load all data(44 uterances z-10 2male and 2female)
data = np.load('lab2_data.npz',allow_pickle=True)['data']
print("data of length:",len(data) )
print(data[1].keys())
print("============")

# Load parameters
phoneHMMs_all = np.load('lab2_models_all.npz',allow_pickle=True)['phoneHMMs'].item()
phoneHMMs_one = np.load('lab2_models_onespkr.npz',allow_pickle=True)['phoneHMMs'].item()
print("phoneme HMM models:")
print(list(sorted(phoneHMMs_one.keys())))
print(phoneHMMs_one['sp'].keys())


data of length:44
dict_keys(['filename', 'samplingrate', 'gender', 'speaker', 'digit', 'repetition', 'samples', 'lmfcc'])
phoneme HMM models:
['ah', 'ao', 'ay', 'eh', 'ey', 'f', 'ih', 'iy', 'k', 'n', 'ow', 'r', 's', 'sil', 'sp', 't', 'th', 'uw', 'v', 'w', 'z']
dict_keys(['name', 'startprob', 'transmat', 'means', 'covars'])


In [4]:
hmm1 = phoneHMMs_one['ah']
hmm2 = phoneHMMs_one['ao']
print("A:")
print(hmm1['transmat'])
print("A:")
print(hmm2['transmat'])
print("Pi:")
print(hmm1['startprob'])
print("Pi:")
print(hmm2['startprob'])
print("\n==========================================================")
print("==========================================================\n")
twoHMms=concatTwoHMMs(hmm1, hmm2)
print("A:")
print(twoHMms['transmat'])
print("Pi:")
print(twoHMms['startprob'])


A:
[[0.6829823 0.3170177 0.        0.       ]
 [0.        0.6620713 0.3379287 0.       ]
 [0.        0.        0.8005023 0.1994978]
 [0.        0.        0.        1.       ]]
A:
[[0.8853924 0.1146077 0.        0.       ]
 [0.        0.7501141 0.2498859 0.       ]
 [0.        0.        0.8315453 0.1684547]
 [0.        0.        0.        1.       ]]
Pi:
[1. 0. 0. 0.]
Pi:
[1. 0. 0. 0.]


A:
[[0.6829823 0.3170177 0.        0.        0.        0.        0.       ]
 [0.        0.6620713 0.3379287 0.        0.        0.        0.       ]
 [0.        0.        0.8005023 0.1994978 0.        0.        0.       ]
 [0.        0.        0.        0.8853924 0.1146077 0.        0.       ]
 [0.        0.        0.        0.        0.7501141 0.2498859 0.       ]
 [0.        0.        0.        0.        0.        0.8315453 0.1684547]
 [0.        0.        0.        0.        0.        0.        1.       ]]
Pi:
[1. 0. 0. 0. 0. 0. 0.]
